const COMPRESSOR_INITIAL_VALUES = {
  threshold: -80,
  knee: 30,
  ratio: 12,
  attack: 0.003,
  release: 0.25
};
const INITIAL_INPUT_GAIN_VALUE = 1;
const INITIAL_OUTPUT_GAIN_VALUE = 1;

const ANALYSER_DISPLAY = {
  BACKGROUND_COLOR: '#020617',
  INPUT_BAR_COLOR: '#db2777',
  OUTPUT_COLOR: '#9d174d'
};

export const SETTINGS = {
  COMPRESSOR_INITIAL_VALUES,
  INITIAL_INPUT_GAIN_VALUE,
  INITIAL_OUTPUT_GAIN_VALUE,
  ANALYSER_DISPLAY
};
